### ISSUE TITLE
Result

### ISSUE THREAD

**Issue by Mrlong12** [ChunbiaoZhu/ACVR2017#1]
Do you have the result on the dataset*1?

**Comment by ChunbiaoZhu** [comment]
Hi, you can use the source code to obtain the results on other datasets, thx!

**Comment by Mrlong12** [comment]
ok, if the depth not 0-1 ,need I Normalize it ?

**Comment by ChunbiaoZhu** [comment]
I forget how I did at that time, so, I suggest you try all the possible operations to remain the best results, thanks for your contributions!

**Comment by Mrlong12** [comment]
ok
